### ISSUE TITLE
Multiline expect/equal

### ISSUE THREAD

**Issue by rstacruz** [scottcorgan/tap-out#21]
Doing this with tape:

```js
t.deepEqual({a:1, b:2}, {a:1, b: 3})
```

Gets you this:

```yaml
    operator: deepEqual
    expected: |-
      { a: 1, b: 2 }
    actual: |-
      { a: 1, b: 3 }
    at: Test.<anonymous> (/Users/rsc/Projects/a/b/test.js:12:5)
```

Which becomes `|-` in the failures:

```js
tap.on('output', function (res) {
  res.fail[0].error.expected === '|-'
  res.fail[0].error.actual === '|-'
})
```

I'd have expected it to be more like `'{a: 1, b: 2}\n'`. Looks like it needs to be parsed via [js-yaml](https://www.npmjs.com/package/js-yaml) or similar.
